### ISSUE TITLE
How can I view the video as a 360 degree without Headset using VLC etc on a desktop?

### ISSUE THREAD

**Issue by sampreetucalgary07** [Telecommunication-Telemedia-Assessment/AVT-360-8K#1]

**Comment by sfremerey** [comment]
Hello, you could either watch it using your favourite video player, then you just see the ERP projection of these videos.
To get a proper 360° view, you need to use a 360° video player, for example https://store.steampowered.com/app/837380/DeoVR_Video_Player or for Windows you could also consider https://potplayer.daum.net 
I don't have any recommendations for Linux or MacOS.

**Comment by sampreetucalgary07** [comment]
Thanks for the reply. Any recommendations for MacOS? Like because I don't think so it will work when uploaded to youtube like other 360 videos are out there? which can I watched from normal browsers.
